import type {
  AcceptanceCriterion,
  Phase,
  Plan,
  Risk,
  Task,
} from "@pm-go/contracts";

/**
 * Render a Plan as a deterministic Markdown document.
 *
 * Guarantees:
 * - No I/O, no timestamps injected — the only timestamp in the output
 *   is `plan.createdAt`.
 * - Iteration order is fully deterministic: phases by `index` ascending,
 *   tasks within a phase by the phase's `taskIds` order (with a stable
 *   fallback to `plan.tasks` order for unknown ids), risks by
 *   `plan.risks` order.
 * - Byte-identical output for identical inputs.
 * - Empty optional fields (e.g. missing `acceptanceCriteria`) are
 *   rendered as omitted bullets rather than `undefined`.
 * - The `## Risks` section is omitted entirely when `plan.risks` is
 *   empty.
 */
export function renderPlanMarkdown(plan: Plan): string {
  const lines: string[] = [];

  lines.push(`# ${plan.title}`);
  lines.push("");
  lines.push(`**Plan ID:** ${plan.id}`);
  lines.push(`**Status:** ${plan.status}`);
  lines.push(`**Created:** ${plan.createdAt}`);
  lines.push("");
  lines.push("## Summary");
  lines.push(plan.summary);
  lines.push("");
  lines.push("## Phases");

  const tasksById = new Map<string, Task>(plan.tasks.map((t) => [t.id, t]));
  const orderedPhases = [...plan.phases].sort((a, b) => a.index - b.index);

  for (const phase of orderedPhases) {
    lines.push("");
    lines.push(`### Phase ${phase.index}: ${phase.title}`);
    lines.push(`**ID:** ${phase.id}`);
    lines.push(`**Status:** ${phase.status}`);
    lines.push(`**Integration branch:** ${phase.integrationBranch}`);
    lines.push("");
    lines.push(phase.summary);
    lines.push("");
    lines.push("#### Tasks");

    const phaseTasks = resolvePhaseTasks(phase, tasksById, plan.tasks);
    if (phaseTasks.length === 0) {
      lines.push("");
      lines.push("_No tasks in this phase._");
      continue;
    }
    for (const task of phaseTasks) {
      lines.push("");
      renderTask(lines, task);
    }
  }

  if (plan.risks.length > 0) {
    lines.push("");
    lines.push("## Risks");
    for (const risk of plan.risks) {
      lines.push("");
      renderRisk(lines, risk);
    }
  }

  lines.push("");
  lines.push("---");
  lines.push(
    "_Generated by the pm-go planner. Source of truth is the structured Plan object._",
  );

  // Ensure a single trailing newline for POSIX-friendly byte-identical output.
  return `${lines.join("\n")}\n`;
}

function resolvePhaseTasks(
  phase: Phase,
  tasksById: Map<string, Task>,
  allTasks: readonly Task[],
): Task[] {
  const ordered: Task[] = [];
  const seen = new Set<string>();
  for (const taskId of phase.taskIds) {
    const task = tasksById.get(taskId);
    if (task && task.phaseId === phase.id) {
      ordered.push(task);
      seen.add(task.id);
    }
    // Missing ids in taskIds are intentionally skipped (don't crash).
  }
  // Append any tasks that claim this phase via phaseId but aren't listed
  // in taskIds — keeps the render authoritative even if the two sources
  // drift.
  for (const task of allTasks) {
    if (task.phaseId === phase.id && !seen.has(task.id)) {
      ordered.push(task);
      seen.add(task.id);
    }
  }
  return ordered;
}

function renderTask(lines: string[], task: Task): void {
  const header =
    `- **${task.slug}** \u2014 ${task.title} ` +
    `(\`${task.kind}\`, risk: \`${task.riskLevel}\`)`;
  lines.push(header);
  const scopeIncludes = task.fileScope.includes ?? [];
  if (scopeIncludes.length > 0) {
    lines.push(`  - Scope: ${scopeIncludes.join(", ")}`);
  }
  if (typeof task.budget?.maxWallClockMinutes === "number") {
    lines.push(`  - Budget: ${task.budget.maxWallClockMinutes} min`);
  }
  if (task.acceptanceCriteria.length > 0) {
    lines.push("  - Acceptance criteria:");
    for (const criterion of task.acceptanceCriteria) {
      renderAcceptanceCriterion(lines, criterion);
    }
  }
}

function renderAcceptanceCriterion(
  lines: string[],
  criterion: AcceptanceCriterion,
): void {
  lines.push(
    `    - ${criterion.description} (required: ${criterion.required})`,
  );
}

function renderRisk(lines: string[], risk: Risk): void {
  lines.push(
    `- **[${risk.level}]** ${risk.title} \u2014 ${risk.description}`,
  );
  lines.push(`  - Mitigation: ${risk.mitigation}`);
  lines.push(
    `  - Human approval required: ${risk.humanApprovalRequired ? "yes" : "no"}`,
  );
}
